### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by danibs** [tesseract-ocr/tessdoc#108]
In https://github.com/tesseract-ocr/tessdoc/blob/main/ImproveQuality.md#noise-removal there are broken links like:
- using the [configuration variable](https://github.com/tesseract-ocr/tessdoc/blob/main/ControlParams)
- For more information see [the FAQ](https://github.com/tesseract-ocr/tessdoc/blob/main/FAQ-Old#is-there-a-minimum-text-size-it-wont-read-screen-text)

**Comment by zdenop** [comment]
thanks - fixed.
