### ISSUE TITLE
PDF workflow issues

### ISSUE THREAD

**Issue by kerim** [tesseract-ocr/tessdoc#113]
How can I OCR an entire PDF and save as an OCR'd PDF in an efficient manner?

I hope this is the correct place to ask this question. If not, please let me know where would be better.

I have a large scan which is a combination of Hindi and English text. 

I was able to install Tesseract OCR and the hindi language models via Homebrew on my MacBook.

I was also able to test it against a single TIEFF file using the following command:

tesseract "file1.TIFF" out1 -l eng+hin PDF

It produced a PDF that had selectable text.

So far, so good.

However, I don't want to have to OCR each page of my PDF. I don't mind exporting my PDF as a folder TIFF files. In fact, I've already done that. But I would like Tesseract to scan the entire folder and save the output as a single PDF. Is that possible. Or, better yet, can it just work with the PDF directly?

Thanks!

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

**Comment by stweil** [comment]
Short hint: use `ocrmypdf` (available for Homebrew). That should solve your requirements.
