### ISSUE TITLE
Debian repository notesalexp.org down

### ISSUE THREAD

**Issue by simepy** [tesseract-ocr/tessdoc#115]
Hi !,

The URL to get Tesseract 5 for Debian looks down : https://notesalexp.org/tesseract-ocr/packages5/
It will probably be restored soon, but it will be good to have some alternative.

Do you have an alternative to get Debian Tesseract 5 ?
I think this minor should be added to the doc.

For the other Linux distribution, have some alternative here : https://github.com/tesseract-ocr/tessdoc/issues/85

**Comment by stweil** [comment]
5.3.0 is available in Debian stable.
