### ISSUE TITLE
Assertion failure when using the legacy ara.traineddata in latest tesseract version.

### ISSUE THREAD

**Issue by girikum** [tesseract-ocr/tessdoc#117]
I downloaded the legacy arabic model file from your documentation here: https://tesseract-ocr.github.io/tessdoc/tess3/Data-Files.html

When I use the model in the latest tesseract version with OEM mode as 0, I see an assertion failure. 

```
tesseract inputImage.jpg outputText -l ara --oem 0
mgr->GetComponent(TESSDATA_INTTEMP, &fp):Error:Assert failed:in file src/classify/adaptmatch.cpp, line 539
Illegal instruction
```

Is this a bug in the tessdata file or the latest tesseract version?

**Comment by stweil** [comment]
It's a bug that the latest Tesseract raises an assertion instead of reporting an old format which is obviously no longer supported. Why do you want to use a legacy model for Arabic? I don't expect that it will work good.
