### ISSUE TITLE
`image_to_data` result doesn't match `image_to_string`

### ISSUE THREAD

**Issue by youjin-c** [tesseract-ocr/tessdoc#123]
I found that `image_to_data` misses many entities that `image_to_string ' could get.
I would like to know if this only happens to me or if there is any reason for that.

**Comment by funny2008** [comment]
how are you

**Comment by zdenop** [comment]
Because Tesseract does not offer either `image_to_string` or `image_to_data` => you are posting the question in the wrong place.

**Comment by youjin-c** [comment]
@zdenop omg thanks for letting me know.
