### ISSUE TITLE
Reading library spine covers

### ISSUE THREAD

**Issue by tacman** [tesseract-ocr/tessdoc#127]
I have what seems to be an "easy" image to OCR, but it's coming out gibberish.  What can I do improve this?

![spine](https://github.com/tesseract-ocr/tessdoc/assets/619585/8adfc572-2d49-4059-8e04-f90fc3b32288)
![code-only](https://github.com/tesseract-ocr/tessdoc/assets/619585/9893844d-ba6d-4386-b47a-3d96f0e31ba7)

I've only ever downloaded the software and used the command line (which works great with a lot of full-page text!)  So I'm not even sure if I can find the font and train this.

Thanks.

**Comment by amitdo** [comment]
Please use our forum for asking questions.
