### ISSUE TITLE
Issue with TESSDATA_PREFIX and Symbolic Links on macOS Ventura Using Homebrew

### ISSUE THREAD

**Issue by carlosdeoncedos** [tesseract-ocr/tessdoc#128]
### Environment:

- Operating System: macOS Ventura 13.6.1, Apple M2 Pro
- Tesseract Version: 5.3.4
- Installation Method: Homebrew
- Language Files: Installed via brew install tesseract-lang

### Issue
I encountered an issue where Tesseract could not load the Spanish language data (spa.traineddata) despite the file being correctly installed and the TESSDATA_PREFIX environment variable being set to point to the directory containing the tessdata folder (/opt/homebrew/share). This issue persisted even though the spa.traineddata file exists and has appropriate permissions. The error message received was:

>_Error opening data file /opt/homebrew/share/spa.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'spa'
Tesseract couldn't load any languages!
Could not initialize tesseract._

I did the following steps to try to solve this issue:
1. Verified the existence and permissions of spa.traineddata.
2. Confirmed that TESSDATA_PREFIX was correctly set (/opt/homebrew/share).
3. Noted that spa.traineddata is a symbolic link pointing to the actual file in the Homebrew Cellar, which might be causing the issue.

### Solution:
As a workaround, specifying the --tessdata-dir option directly in the command (tesseract test_image.png out --tessdata-dir /opt/homebrew/share/tessdata -l spa) successfully bypassed the issue, indicating the problem might be related to how Tesseract resolves the TESSDATA_PREFIX environment variable or handles symbolic links in this context.

To streamline the process, I created an alias in my zshrc profile to include the --tessdata-dir option automatically, allowing me to use Tesseract without manually specifying the path each time.

### Questions/Feedback:

1. Is there a known issue with how Tesseract resolves symbolic links or environment variables on macOS, specifically when installed via Homebrew?
2. Are there recommended steps to avoid this issue, ensuring Tesseract correctly locates the language files without needing to specify --tessdata-dir for each command?
3. Any advice or fixes that could make this configuration more seamless would be greatly appreciated.

Thank you for your support and for developing such a powerful tool.

**Comment by stweil** [comment]
Try `TESSDATA_PREFIX=/opt/homebrew/share/tessdata` or even better don't use `TESSDATA_PREFIX` at all. Most distributions should not require it.

**Comment by stweil** [comment]
The error message "Error opening data file /opt/homebrew/share/spa.traineddata" is correct: that file or symlink does not exist in a Homebrew installation.

**Comment by carlosdeoncedos** [comment]
@stweil , I remove `TESSDATA_PREFIX` as suggested and it worked perfectly!  Thanks for your quick response!  Since everything is working now, I will close this issue.
