### ISSUE TITLE
Missing example images in ImproveQuality

### ISSUE THREAD

**Issue by zacharysyoung** [tesseract-ocr/tessdoc#18]
The *Dilation and Erosion* section seems very self explanatory, I believe I understand the principle and its practice.  It also lists a before-and-after image set that is not in the repo.

Can these images be added to the repo and properly integrated into the documentation? I think they'd just be more helpful.

**Comment by stweil** [comment]
@thadguidry, you added that documentation to the Wiki. Can you provide those two missing images?

**Comment by thadguidry** [comment]
@stweil Done! (converted them to PNG also for consistency with others)

**Comment by thadguidry** [comment]
@zacharysyoung Glad you thought that section I added a few months ago is useful to you! I spent a whole weekend on researching it :-)

**Comment by zacharysyoung** [comment]
@thadguidry, yeah, well, I thought I understood the effects of applying erosion, but running Tesseract over your sample images I can see it's not so cut-and-dry. Thank you for your efforts :)

**Comment by thadguidry** [comment]
@zacharysyoung Oh there is so much "cutting" and "bleeding" when working with older historical texts :-)
