### ISSUE TITLE
Unable to tesseract text from cropped image

### ISSUE THREAD

**Issue by Ptstset132** [tesseract-ocr/tessdoc#23]
![MTG_719_530_1](https://user-images.githubusercontent.com/29592864/90388820-0f0e2680-e0a6-11ea-8fa8-417dd21ccebb.jpg)
Here, we have cropped image from main source. I can't able to extract the text and numbers properly. I have checked with tesseract-5 & 4, also increased the image resolution and have done with few pre-processing steps but can't able to get accurate ocr result.( inst.no and off rec 0719 page 0530 not extracted)

**Comment by zdenop** [comment]
Do all necessary preprocessing not just few. And use tessract user forum for asking support.

**Comment by Ptstset132** [comment]
> Do all necessary preprocessing not just few. And use tessract user forum for asking support.

Done with all necessary pre-processing steps but still can't able to extract the text and numbers properly in tesseract.
