### ISSUE TITLE
pytesseract.pytesseract.TesseractError: (1, 'Error opening data file \\Programing Languages\\Python\\Tesseract-OCR\\eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')

### ISSUE THREAD

**Issue by Aksahy2048** [tesseract-ocr/tessdoc#24]
import pytesseract
pytesseract.pytesseract.tesseract_cmd = r'D:\Programing Languages\Python\Tesseract-OCR\tesseract.exe'
from PIL import Image

img = Image.open('textHand2.png')
text = pytesseract.image_to_string(img)

print(text)

error:

return {
  File "D:\Programing Languages\Python\lib\site-packages\pytesseract\pytesseract.py", line 357, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "D:\Programing Languages\Python\lib\site-packages\pytesseract\pytesseract.py", line 266, in run_and_get_output
    run_tesseract(**kwargs)
  File "D:\Programing Languages\Python\lib\site-packages\pytesseract\pytesseract.py", line 242, in run_tesseract
    raise TesseractError(proc.returncode, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, 'Error opening data file \\Programing Languages\\Python\\Tesseract-OCR\\eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')

**Comment by zdenop** [comment]
1. We do not provide support for 3rd sw (pytesseract).
2. Read the error message and fix your settings.
3. Search internet is this very common user problem.
