### ISSUE TITLE
Unable to tesseract text from cropped image

### ISSUE THREAD

**Issue by Ptstset132** [tesseract-ocr/tessdoc#25]
Here, we have cropped image from main source. I can't able to extract the text and numbers properly. I have checked with tesseract-5 & 4, also increased the image resolution and have done with pre-processing steps but can't able to get accurate ocr result.( inst.no and off rec 0719 page 0530 not extracted)
![MTG_719_530_1](https://user-images.githubusercontent.com/29592864/90478804-4c78bf80-e14b-11ea-95bf-0136b911addf.jpg)

**Comment by zdenop** [comment]
duplicate #23
