### ISSUE TITLE
OCR not working with zoomed in windows

### ISSUE THREAD

**Issue by Shrexy-Dev-Team** [tesseract-ocr/tessdoc#26]
I have a 1440p laptop and in setting i have changed the zoom level to 175%. Unfortunately, this means that when i try to use tesseract ocr that the image capture reference is offset from the selector. I would really appreciate help with this, as i am a ovice to c# and this program captured my interest.

**Comment by zdenop** [comment]
This is not tesseract issue. please use relevant forum for asking support.
