### ISSUE TITLE
tessdoc FAQ - table of contents out of date

### ISSUE THREAD

**Issue by engineerchange** [tesseract-ocr/tessdoc#27]
On this [page](https://tesseract-ocr.github.io/tessdoc/FAQ.html), some of the sections below don't have an appropriate Table of Contents link. For instance, if you ctrl+f 'improve ocr results', you can note it has a section but the table of contents doesn't have the appropriate anchor hyperlink.

**Comment by stweil** [comment]
Thank you for reporting. Do you want to send a pull request which fixes the table of contents?

**Comment by engineerchange** [comment]
Sure, I'd be happy to take a look this weekend. Thanks!
