### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by Robyer** [tesseract-ocr/tessdoc#42]
I was looking at the docs page https://tesseract-ocr.github.io/tessdoc/ and there is broken link:

- **External Projects / AddOns** navigates to https://tesseract-ocr.github.io/AddOns.md which doesn't exists -> it should be https://tesseract-ocr.github.io/tessdoc/AddOns.html (change to .html and missing tessdoc part)

Similar situation is on the AddOns page on first link:

- **User Projects - 3rd Party** navigates to https://tesseract-ocr.github.io/tessdoc/User-Projects-%E2%80%93-3rdParty.md but it should be https://tesseract-ocr.github.io/tessdoc/User-Projects-%E2%80%93-3rdParty.html (change to .html)

I haven't checked other pages, so it's possible there are similar issues with these ***.md** instead of ***.html**

**Comment by Robyer** [comment]
I sent PR (two separate ones as I did it via Github website) to fix these two links.

**Comment by Shreeshrii** [comment]
Thanks!
