### ISSUE TITLE
Compilation guide for various platforms - Windows - Build training tools

### ISSUE THREAD

**Issue by HotDenim** [tesseract-ocr/tessdoc#47]
The Windows instructions of the 'Build Training Tools' does not work:

[http://tesseract-ocr.github.io/tessdoc/Compiling.html#windows](http://tesseract-ocr.github.io/tessdoc/Compiling.html#windows)

I think it is due to the [https://cppan.org ](https://cppan.org )website/network being discontinued, and being replaced with _Software Network / SW_.

How can I obtain the Training Tools for windows (32-bit and 64-bit) ? (Better build them myself).

Also can the documentation be updated for this issue ?

**Comment by Shreeshrii** [comment]
@egorpugin Please delete the deprecated info regrading compiling on windows.

@HotDenim Latest Windows binaries with training tools can be downloaded from https://github.com/UB-Mannheim/tesseract/wiki

Though, for training, I would recommend using Linux.

**Comment by egorpugin** [comment]
Done.

**Comment by Shreeshrii** [comment]
Thanks!

**Comment by HotDenim** [comment]
> Done.

The new instructions do not work. I followed then, and while SW was executing, it stopped with an error:

> [2718/3758] generate: "C:/Users/User/.sw/storage/pkg/1f/e0/12aa/obj/bld/179681/bd/gobject/glib-enumtypes.c"
> Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:764, function execute1: When executing: generate: "C:/Users/User/.sw/storage/pkg/1f/e0/12aa/obj/bld/179681/bd/gobject/glib-enumtypes.c"
> command failed: exit code = -1073741515 (0xC0000135): The specified module could not be found.
> Total errors: 1

This happened for the 4.1 Branch and the Master branch. (I would like to compile the 4.1 branch).

**Comment by egorpugin** [comment]
Add `-k 1000` options, run.
Then add `--trace 2> log.txt` options and send log.

**Comment by egorpugin** [comment]
Try to run `sw build org.sw.demo.google.tesseract.training.text2image-master -sfc --trace 2> log.txt`
If there are errors:
1. Post log.
2. In `.sw\rsp` run the latest `.bat` file by double click and post screenshot of error message. There will be dll name that is missing.

**Comment by egorpugin** [comment]
Oh, the missing component is on MS side, not sw.
Can you show `winver` command output? Win+R, type `winver`, Enter.

**Comment by egorpugin** [comment]
Can you send me that `.bat` file you've run also?

**Comment by egorpugin** [comment]
See this link - https://answers.microsoft.com/en-us/windows/forum/windows8_1-pictures-musicapp/api-ms-win-crt-runtime-l1-1-0dll-is-missing/b593b94e-6691-423b-a586-0b7f10131e35?auth=1

Try to install VS2015 redist. It is strange, because you have VS and WinSDK installed.

**Comment by HotDenim** [comment]
@egorpugin

Winver:

![WinVer](https://user-images.githubusercontent.com/14130510/110538823-6516ea00-811c-11eb-82d1-65b78f39d1d4.png)

BAT file (renamed to .TXT to enable attaching):

[1461694303201023788.bat.txt](https://github.com/tesseract-ocr/tessdoc/files/6111450/1461694303201023788.bat.txt)

?

**Comment by HotDenim** [comment]
@egorpugin

installed VS2015 redist. Then tried again (SW Build .) , but still error.

**Comment by egorpugin** [comment]
Also it would be nice if you send `tree` output of `C:\\Program Files (x86)\\Visual Studio 2015` and `C:\\Program Files (x86)\\Microsoft Visual Studio 12.0`.

**Comment by HotDenim** [comment]
@egorpugin

OK will do for next post. Also for` sw build org.sw.demo.google.tesseract.training.text2image-master -sfc --trace 2> log.txt`:

[log.txt](https://github.com/tesseract-ocr/tessdoc/files/6111565/log.txt)

Two .BAT files same date:
![8802815074161298208](https://user-images.githubusercontent.com/14130510/110541754-166b4f00-8120-11eb-91b5-a0bc9b143340.png)
![1461694303201023788](https://user-images.githubusercontent.com/14130510/110541753-153a2200-8120-11eb-8f65-c14d29b23888.png)

[1461694303201023788.bat.txt](https://github.com/tesseract-ocr/tessdoc/files/6111579/1461694303201023788.bat.txt)
[8802815074161298208.bat.txt](https://github.com/tesseract-ocr/tessdoc/files/6111580/8802815074161298208.bat.txt)

**Comment by HotDenim** [comment]
> 1. Win7 WinSDK (6.1 or 6.1A

This ?:

https://www.microsoft.com/en-gb/download/details.aspx?id=8442

It is version 7.1

also 32-bit distribution or 64-bit (I wish to build both).

**Comment by egorpugin** [comment]
> This ?

Yes, try those installers.

**Comment by HotDenim** [comment]
@egorpugin

Attached are the Tree output files (refer to the filenames). 

Also, the _VS 2015 redist_ does **not** include the **_api-ms-win-core-io-l1-1-1.dll_** file.  I downloaded this file separately and installed it, after that the .BAT file now refers to more .DLL error (**_api-ms-win-core-synch-l1-2-1.dll_**). I think these .DLL files are Windows 10 **only** files ?  (see [https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-apis](https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-apis) )

[Program Files (x86), Microsoft Visual Studio 10.0.txt](https://github.com/tesseract-ocr/tessdoc/files/6116193/Program.Files.x86.Microsoft.Visual.Studio.10.0.txt)
[Program Files (x86), Microsoft Visual Studio.txt](https://github.com/tesseract-ocr/tessdoc/files/6116194/Program.Files.x86.Microsoft.Visual.Studio.txt)
[Program Files (x86), Window Kits.txt](https://github.com/tesseract-ocr/tessdoc/files/6116195/Program.Files.x86.Window.Kits.txt)
[Program Files, Microsoft SDK's.txt](https://github.com/tesseract-ocr/tessdoc/files/6116196/Program.Files.Microsoft.SDK.s.txt)
[Program Files (x86), Microsoft SDK's.txt](https://github.com/tesseract-ocr/tessdoc/files/6116197/Program.Files.x86.Microsoft.SDK.s.txt)

 
 
Also, I installed Window 10 64-Bit, new installation, then installed : 
- Cmake
- Git
- SW
- Visual Studio 2019
- VS 2015 Redist
- Windows 7 SDK 7.1 (as found in previous post) - **64-Bit**

And the **Same** error is present.

**Comment by egorpugin** [comment]
> I think these .DLL files are Windows 10 only files ?

Yes, something like this.

The problem is that sw does not use your host config (host - win7 SDK) and uses win10 sdk. Therefore the binaries cannot be started.
I'll try to do quick fixes in sw, maybe we'll be able to get it working.

Can you send me `set` command ouput?

**Comment by HotDenim** [comment]
@egorpugin

> Can you send me `set` command ouput?

`
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\User\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=X
ComSpec=C:\Windows\system32\cmd.exe
FP_NO_HOST_CHECK=NO
HOMEDRIVE=C:
HOMEPATH=\Users\User
LOCALAPPDATA=C:\Users\User\AppData\Local
LOGONSERVER=\\VIRTUALBOX
NUMBER_OF_PROCESSORS=1
OS=Windows_NT
Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3a09
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\User\AppData\Local\Temp
TMP=C:\Users\User\AppData\Local\Temp
USERDOMAIN=VirtualBox
USERNAME=User
USERPROFILE=C:\Users\User
VS100COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools\
windir=C:\Windows
windows_tracing_flags=3
windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log

`

**Comment by HotDenim** [comment]
@egorpugin

> Can you send me `set` command ouput?

Here:

```

ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\Tester\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=X
ComSpec=C:\Windows\system32\cmd.exe
FP_NO_HOST_CHECK=NO
HOMEDRIVE=C:
HOMEPATH=\Users\Tester
LOCALAPPDATA=C:\Users\Tester\AppData\Local
LOGONSERVER=\\VIR
NUMBER_OF_PROCESSORS=4
OS=Windows_NT
Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3a09
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\Tester\AppData\Local\Temp
TMP=C:\Users\Tester\AppData\Local\Temp
USERDOMAIN=X
USERNAME=Tester
USERPROFILE=C:\Users\Tester
VS100COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools\
windir=C:\Windows
windows_tracing_flags=3
windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log

```

**Comment by egorpugin** [comment]
Ok, I'm sending a new binary with some updates. Unpack and replace old sw.exe. Run the command and post logs.
First, we'll try to check if winsdk7 is detected by sw.
After that we need to provide correct host settings to sw.

[sw.client.sw-1.0.0.exe.zip](https://github.com/tesseract-ocr/tessdoc/files/6116934/sw.client.sw-1.0.0.exe.zip)

**Comment by HotDenim** [comment]
> Ok, I'm sending a new binary with some updates. Unpack and replace old sw.exe. Run the command and post logs.
> First, we'll try to check if winsdk7 is detected by sw.
> After that we need to provide correct host settings to sw.
> 
> [sw.client.sw-1.0.0.exe.zip](https://github.com/tesseract-ocr/tessdoc/files/6116934/sw.client.sw-1.0.0.exe.zip)

Which Command, and which logs ?.

**Comment by HotDenim** [comment]
@egorpugin

Log File:

[log.txt](https://github.com/tesseract-ocr/tessdoc/files/6118161/log.txt)

**Comment by egorpugin** [comment]
Can you email me to solve this faster?
egor.pugin at gmail.com

**Comment by egorpugin** [comment]
Try this binary, send log.

[sw.client.sw-1.0.0.exe.zip](https://github.com/tesseract-ocr/tessdoc/files/6118277/sw.client.sw-1.0.0.exe.zip)

**Comment by HotDenim** [comment]
> Can you email me to solve this faster?
> egor.pugin at gmail.com

Problems with email , at the moment.

**Comment by HotDenim** [comment]
> Try this binary, send log.
> 
> [sw.client.sw-1.0.0.exe.zip](https://github.com/tesseract-ocr/tessdoc/files/6118277/sw.client.sw-1.0.0.exe.zip)

@egorpugin

Log File:
[Uploading log.txt…]()

**Comment by egorpugin** [comment]
Try this binary, send log.
[sw.client.sw-1.0.0.exe.zip](https://github.com/tesseract-ocr/tessdoc/files/6118606/sw.client.sw-1.0.0.exe.zip)

**Comment by egorpugin** [comment]
I've checked some things further, it seems we can't fix this issue on win7 right now. (Next sw version is in progress - it should fix the issue.)
So, you have to build it on win10.

**Comment by HotDenim** [comment]
When will next version be released?

**Comment by HotDenim** [comment]
How do I build it in Windows 10., the commands ?), for 32-Bit & 64-Bit, and Static & Dynamic Libraries ?. And version 4.1! 

Also do I need to download the source via GIT first ?

**Comment by egorpugin** [comment]
> When will next version be released?

After some core algorithms is developed.

> How do I build it in Windows 10

Same instructions.
1. Download sources.
2. `sw build -platform x86,x64 -static -shared`  Combine flags as you wish.
3. Output files will be in `.sw\out\some hash`

**Comment by HotDenim** [comment]
> > When will next version be released?
> 
> After some core algorithms is developed.
> 
> > How do I build it in Windows 10
> 
> Same instructions.
> 
> 1. Download sources.
> 2. `sw build -platform x86,x64 -static -shared`  Combine flags as you wish.
> 3. Output files will be in `.sw\out\some hash`

So for Tesseract 4.1 I will need to download from GIT the source code. first ?, for 4.1 ?. **_Yes?_**,  and does SW also work with 4.1 ?.
