### ISSUE TITLE
Searchable pdf output: Broken PDF file

### ISSUE THREAD

**Issue by Chealer** [tesseract-ocr/tessdoc#48]
The _Searchable pdf output_ section of [the Command Line Usage page](https://tesseract-ocr.github.io/tessdoc/Command-Line-Usage) ends with a PDF file which displays broken (just the file name and sometimes a file icon), whether in Google Chrome 91 or in Mozilla Firefox:
![image](https://user-images.githubusercontent.com/486141/120036442-24699700-bfce-11eb-99a7-03f5c3a4e3f7.png)

**Comment by zdenop** [comment]
Should be fixed:

![image](https://user-images.githubusercontent.com/574156/120114757-f4162a00-c180-11eb-9571-911f8356501f.png)
