### ISSUE TITLE
Failed to find library "tesseract41.dll" for platform x86

### ISSUE THREAD

**Issue by supermine-xiao** [tesseract-ocr/tessdoc#49]
I've tried everything I can think of,but nothing. 
I also installed "c++2015 edistributable(x86) - 14.0.24215" and "c++2005 edistributable";
I tried to install tesseract41.dll by "regsvr32 " but install fail;

**Comment by zdenop** [comment]
1. This is issue tracker for tesseract documentation. Your "problem" is not related to it.
2. Windows XP is dead/unsupported OS.
