### ISSUE TITLE
Do CUDA GPUs improve Tesseract 4.x LSTM performance?

### ISSUE THREAD

**Issue by EtagiBI** [tesseract-ocr/tessdoc#5]
Hello,

According to [this article](https://developer.nvidia.com/discover/lstm), it's possible to significantly improve LSTM performance using CUDA GPUs. Since Tesseract 4.x uses new LSTM-based core, is it true that it should perform better with CUDA-powered GPUs?

If yes, it would be helpful to have a description (or a note at least) in documentation.

**Comment by stweil** [comment]
Tesseract would indeed be much faster with a GPU. You just have to add the necessary code which currently does not exist.

And please use the user forum for questions.
