### ISSUE TITLE
language selection not available and error while processing

### ISSUE THREAD

**Issue by herrachamp** [tesseract-ocr/tessdoc#50]
There are two issues I am facing.
First: I cannot select language for ocr (check image 1)
Second: After clicking OK button I am getting an error. (check image 2)
I think second issue is occurring due to the first issue. Am not sure.
I need your assistance.
Please help me.
I have attached both the images.
![Image 1](https://user-images.githubusercontent.com/85825674/122269621-0de29b80-cefb-11eb-8d6c-2ec308943a48.png)
![Image 2](https://user-images.githubusercontent.com/85825674/122269628-0f13c880-cefb-11eb-8f03-47158c4609e1.png)

**Comment by zdenop** [comment]
We do not provide support for 3rd party projects. Please contact its authors.
