### ISSUE TITLE
404 for tessdoc

### ISSUE THREAD

**Issue by taomanwai** [tesseract-ocr/tessdoc#58]
### Environment

* **Tesseract Version**: Latest version of tessdoc on 2021-09-13
* **Commit Number**: NA
* **Platform**: Win10, Chrome v91.0.4472.164 (Official Build) (64-bit)

### Current Behavior:
404 error on Tesseract documentation site (https://tesseract-ocr.github.io/tessdoc/)

### Expected Behavior:
Tesseract documentation site will show detail information of Tesseract

### Suggested Fix:
NA

**Comment by stweil** [comment]
I moved the issue from tesseract to tessdoc. Issue #57 has the same background. Therefore I close the issue here and answer for issue #57.
