### ISSUE TITLE
Fails to stop text retrieving process when timeout hits before completing text retrieving process.

### ISSUE THREAD

**Issue by divyangashah** [tesseract-ocr/tessdoc#6]
Environment

**Tesseract Version:** 4.0.0.0-beta3
**Platform:** 64-bit

**Current Behavior:** we are providing timeout at page level for tesseract ocr operation for pdf/image files. It works fine when timeout=0. but, apart from that for ex., 2 mins. or 5 mins. it fails with unexpected error and crashed whole application

**Expected Behavior:** If we provide a timeout and page is not able to processed within timeout limit it should stop retrieving text for that page and go further for the next page.

**Comment by stweil** [comment]
Version 4.0.0 is unsupported. Please try again with a supported version and reopen this issue if the problem still exists.

**Comment by divyangashah** [comment]
@stweil I am using tesseract in c#. so, I have used latest dll available for tesseract in C#.

so, any suggestion on that?

**Comment by stweil** [comment]
So you are working on Windows. You should have mentioned that in your report.

For Windows I suggest to build your own Tesseract DLL, or maybe even better build a normal library and link statically against that.

**Comment by stweil** [comment]
This issue is not related to `tessdoc`, but to `tesseract`, so I transfer it.
