### ISSUE TITLE
TesseractStudio.Net is not available anymore

### ISSUE THREAD

**Issue by LightTemplar** [tesseract-ocr/tessdoc#66]
I suggest to remove TesseractStudio.Net from "User-Projects-–-3rdParty.md" because the project seems abandoned and you can't even get any installers or executable or source code from anywhere.

**Comment by blackholeearth** [comment]
https://github.com/tesseract-ocr/tessdoc/pull/71

**Comment by Shreeshrii** [comment]
Looks like the link needs to be updated. See https://www.opait.com/TessStudio/index.html

**Comment by blackholeearth** [comment]
added  website url

**Comment by amitdo** [comment]
Fixed in #71.
