### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by seanlally8** [tesseract-ocr/tessdoc#67]
Hello there,

Just noticed that the link is dead in this sentence: "Please read the Implementation introduction before delving too deeply into the training process, and the same note as for training Tesseract 3.04 applies:" (Under the ReadMe section, "Before You Start"). 

This is the current link: https://github.com/tesseract-ocr/tessdoc/blob/main/tess4/NeuralNetsInTesseract4.00

And I believe it should be this: https://github.com/tesseract-ocr/tessdoc/blob/main/tess4/NeuralNetsInTesseract4.00.md

**Comment by zdenop** [comment]
thanks. Fixed.
