### ISSUE TITLE
Could macOS compile tesseract 5.1.0?

### ISSUE THREAD

**Issue by wang234-source** [tesseract-ocr/tessdoc#77]
I hope to use the LSTM file to train my data but it seems there are only tutorial on Linux?
 Could macOS compile tesseract 5.1.0?

**Comment by stweil** [comment]
https://tesseract-ocr.github.io/tessdoc/Compiling.html#macos

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
