### ISSUE TITLE
Debian repository notesalexp.org down?

### ISSUE THREAD

**Issue by razvi8** [tesseract-ocr/tessdoc#85]
Our container builds are failing to install tesseract - and it looks like notesalexp.org site is down - is anyone aware of an alternative package repository?

**Comment by amitdo** [comment]
You didn't mention a distro.

Ubuntu:
* https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr
* https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr-daily
* https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr-devel

**Comment by amitdo** [comment]
Other distros:
https://build.opensuse.org/project/show/home:Alexander_Pozdnyakov:tesseract5

**Comment by amitdo** [comment]
CC: @AlexanderP

**Comment by amitdo** [comment]
OK, you did mention a distro in the title.

I didn't find an alternative source for Debian.

I

**Comment by AlexanderP** [comment]
hi.
Restore in an hour
