### ISSUE TITLE
error in make

### ISSUE THREAD

**Issue by Geta-meko** [tesseract-ocr/tessdoc#9]
Makefile:1930: recipe for target 'libtesseract.la' failed
make[2]: *** [libtesseract.la] Error 1
make[2]: Leaving directory '/home/get/tesseract'
Makefile:4121: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/get/tesseract'
Makefile:1356: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zdenop** [comment]
1. This not right repository to post issues with building tesseract
2. Information you provided are useless. Nobody can replicate problem from it, nobody can find information about OS and tools you use to build tesseract, version you try to build...
