### ISSUE TITLE
TrainingTesseract-5.md ScrollView & hallucination 404 link

### ISSUE THREAD

**Issue by ChrisHSandN** [tesseract-ocr/tessdoc#91]
Reading through the TrainingTesseract-5.md page and I have come across a few dead links:

[#building-the-training-tools](https://github.com/tesseract-ocr/tessdoc/blob/main/tess5/TrainingTesseract-5.md#building-the-training-tools)
`ScrollView.jar` link goes to 404
Maybe supposed to link to https://tesseract-ocr.github.io/tessdoc/ViewerDebugging ?

[#debug-interval-and-visual-debugging](https://github.com/tesseract-ocr/tessdoc/blob/main/tess5/TrainingTesseract-5.md#debug-interval-and-visual-debugging)
Another `ScrollView.jar` link goes to 404

[#the-hallucination-effect](https://github.com/tesseract-ocr/tessdoc/blob/main/tess5/TrainingTesseract-5.md#the-hallucination-effect)
`Then read the hallucination topic.` link goes to 404
Maybe supposed to link to https://tesseract-ocr.github.io/tessdoc/tess4/The-Hallucination-Effect.html ?

**Comment by zdenop** [comment]
thanks. Fixed (relative paths changed to absolute)
