### ISSUE TITLE
simple question

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [tesseract-ocr/tessdoc#92]
Hello Tesseract ! 

Wow what a pkg you made, it is so awesome. 

I looked at the documentation, looked at various links and FAQs but did not find 

- what are the list of functions of this package ?
- what is **bbox** output actually telling me?  (_my guess is the locations of where word X is located_)
- is there examples of combining output with NLP functions/ pkgs ? 

Thank you.

**Comment by amitdo** [comment]
For the bbox question, see the [hocr spec](http://kba.cloud/hocr-spec/1.2/).

For the the public API, you can see it by opening the files in [include/tesseract](https://github.com/tesseract-ocr/tesseract/tree/main/include/tesseract).

For your last question, we don't have such an example.

If you have a more questions, please use our forum.
